nelmio_api_doc:
  documentation:
    info:
      title: Trajectory Animation Backend (TAB)
      description: Backend documentation for softball pitch trajectories modeling and analysis application.
      version: 0.3.0
    servers:
      - url: https://tranim.nede.cz/api
  html_config:
    stoplight_config:
      layout: responsive
      router: hash
  areas:
    default:
      disable_default_routes: true
